language: go

env:
  CODECOV_TOKEN="f4abe318-f215-4480-9dd4-f4f4fb99e1f0"

go:
  - 1.11.x
  - tip

git:
  depth: 1

before_install:
  - go get -t -v ./...

script:
  - go test -v -bench . -benchmem -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)


